/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17. 3. 29 오후 2:50' with Gradle 2.14.1
 *
 * @author Administrator, @date 17. 3. 29 오후 2:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
